apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqlookupd.fullname" . }}
  labels:
    {{- include "nsqlookupd.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  # So we can access each individual node of the statefulset
  clusterIP: None
  ports:
    - port: 4161
      targetPort: http
      protocol: TCP
      name: http
    - port: 4160
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "nsqlookupd.selectorLabels" . | nindent 4 }}
