{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nsqd.fullname" . }}
  labels:
    {{- include "nsqd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "nsqd.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | trim | indent 2 }}
  minAvailable: 1
{{- end -}}