piVersion: v1
kind: ConfigMap
metadata:
  name: nsq
data:
  nsq-admin.cfg: |
    nsqlookupd_http_addresses = [
      {{- range $key, $value := default dict .Values.postgresqlConfiguration }}
        {{ include nsqd.fullname }}-{{$key}}.{{ include nsqd.fullname}}.{{ .Values.namespace }}:4161
      {{- end }}
    ]
  nsqd.cfg: |-
    nsqlookupd_tcp_addresses = [
      "{{ include nsqd.fullname .}}-.{{ include nsqd.fullname .}}.{{ }}:4160",
      "nsqlookupd-scheduler-1.nsqlookupd-scheduler.scheduler:4160",
      "nsqlookupd-scheduler-2.nsqlookupd-scheduler.scheduler:4160"
    ]
