{{ define "gitops-common.aws-secret-manager-volume" }}
name: {{ . | default "csi-driver-volume" | quote }}
csi:
  driver: secrets-store.csi.k8s.io
  readOnly: true
  volumeAttributes:
    secretProviderClass: "aws-secret-credentials"
{{ end }}

{{ define "gitops-common.aws-secret-manager-volume-mount" }}
name: {{ . | default "csi-driver-volume-mount" | quote }}
mountPath: /mnt/secrets
readOnly: true
{{ end }}

{{ define "gitops-common.aws-secret-manager-env-vars" }}
- name: SECRETS_VOLUME_PATH
  value: /mnt/secrets
{{ end }}

{{ define "gitops-common.aws-secret-manager-env-map" }}
SECRETS_VOLUME_PATH: /mnt/secrets
{{ end }}
