apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.fullname" . }}
  labels:
    {{- include "nsqd.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: 9117
      targetPort: 9117
      protocol: TCP
    {{- end }}
    - name: nsqd-tcp
      port: 4150
      targetPort: 4150
      protocol: TCP
    - name: nsqd-http
      port: 4151
      protocol: TCP
      targetPort: 4151
  selector:
    {{- include "nsqd.selectorLabels" . | nindent 4 }}
