apiVersion: v1
kind: Secret
metadata:
  name: {{ include "op-scim-bridge.fullname" . }}
  labels:
    {{- include "op-scim-bridge.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.scim.secret | nindent 2}}
