# Default values for nsq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nsqadmin:
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      create: true
  nsqd:
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      create: true
  nsqlookupd:
    nameOverride: ""
    fullnameOverride: ""
    serviceAccount:
      create: true

nsqadmin:
  replicaCount: 3
nsqd:
  replicaCount: 3
nsqlookupd:
  replicaCount: 3

